#!/bin/bash
# Set up cross-compilation for Raspberry Pi
# Usage: ./scripts/rpi-setup.sh <target>
#   target: aarch64-unknown-linux-gnu (64-bit) or armv7-unknown-linux-gnueabihf (32-bit)
#
# Run rpi-discover.sh on your RPi first to determine the correct target.

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

# Default to 64-bit ARM (RPi 3/4/5 with 64-bit OS)
TARGET="${1:-aarch64-unknown-linux-gnu}"

echo "=== kr_notebook Cross-Compilation Setup ==="
echo "Target: $TARGET"
echo ""

# Determine linker based on target
case "$TARGET" in
    aarch64-unknown-linux-gnu)
        LINKER="aarch64-linux-gnu-gcc"
        BREW_PACKAGE="aarch64-elf-gcc"
        ;;
    armv7-unknown-linux-gnueabihf)
        LINKER="arm-linux-gnueabihf-gcc"
        BREW_PACKAGE="arm-linux-gnueabihf-binutils"
        ;;
    *)
        echo "Error: Unknown target '$TARGET'"
        echo "Supported targets:"
        echo "  aarch64-unknown-linux-gnu      (RPi 3/4/5 64-bit)"
        echo "  armv7-unknown-linux-gnueabihf  (RPi 2/3/4 32-bit)"
        exit 1
        ;;
esac

# Check if we're on macOS
if [[ "$(uname)" == "Darwin" ]]; then
    echo "[1/4] Checking for cross-compilation toolchain..."

    # Option 1: Use cross (Docker-based, easier)
    if command -v cross &>/dev/null; then
        echo "  'cross' is installed - recommended for cross-compilation"
        USE_CROSS=true
    elif command -v docker &>/dev/null; then
        echo "  Docker found. Installing 'cross'..."
        cargo install cross --git https://github.com/cross-rs/cross
        USE_CROSS=true
    else
        echo "  Docker not found. Will try native cross-compiler..."
        USE_CROSS=false

        # Check for Homebrew cross-compiler
        if ! command -v $LINKER &>/dev/null; then
            echo ""
            echo "  Cross-compiler not found. To install:"
            echo ""
            if [[ "$TARGET" == "aarch64-unknown-linux-gnu" ]]; then
                echo "    # Option 1: Usezig as linker (easiest)"
                echo "    brew install zig"
                echo "    cargo install cargo-zigbuild"
                echo ""
                echo "    # Option 2: Use messense/homebrew-macos-cross-toolchains"
                echo "    brew tap messense/macos-cross-toolchains"
                echo "    brew install aarch64-unknown-linux-gnu"
            else
                echo "    brew tap messense/macos-cross-toolchains"
                echo "    brew install arm-unknown-linux-gnueabihf"
            fi
            echo ""
            echo "  Or install Docker and re-run this script to use 'cross'."
            exit 1
        fi
    fi
else
    echo "[1/4] Linux detected - cross-compilation should work natively"
    USE_CROSS=false
fi

echo ""
echo "[2/4] Adding Rust target..."
rustup target add "$TARGET"

echo ""
echo "[3/4] Creating cargo config..."

mkdir -p "$PROJECT_DIR/.cargo"

# Write cargo config
if [ "$USE_CROSS" = true ]; then
    cat > "$PROJECT_DIR/.cargo/config.toml" << EOF
# Cross-compilation config for Raspberry Pi
# Generated by rpi-setup.sh

[target.$TARGET]
# Using 'cross' for builds (Docker-based)

[build]
# Uncomment to make this target the default:
# target = "$TARGET"
EOF
    echo "  Configured to use 'cross' (Docker-based)"
else
    # Check for zig
    if command -v zig &>/dev/null && command -v cargo-zigbuild &>/dev/null; then
        cat > "$PROJECT_DIR/.cargo/config.toml" << EOF
# Cross-compilation config for Raspberry Pi
# Generated by rpi-setup.sh

[target.$TARGET]
# Using zigbuild for cross-compilation

[build]
# Uncomment to make this target the default:
# target = "$TARGET"
EOF
        echo "  Configured to use cargo-zigbuild"
    else
        cat > "$PROJECT_DIR/.cargo/config.toml" << EOF
# Cross-compilation config for Raspberry Pi
# Generated by rpi-setup.sh

[target.$TARGET]
linker = "$LINKER"

[build]
# Uncomment to make this target the default:
# target = "$TARGET"
EOF
        echo "  Configured linker: $LINKER"
    fi
fi

echo ""
echo "[4/4] Creating deploy config..."
echo ""

# Prompt for deployment settings
read -p "SSH connection (alias or user@host) [raspberry]: " RPI_SSH
RPI_SSH="${RPI_SSH:-raspberry}"

read -p "Install directory on RPi [~/kr_notebook]: " RPI_INSTALL_DIR
RPI_INSTALL_DIR="${RPI_INSTALL_DIR:-~/kr_notebook}"

read -p "Systemd service name [kr_notebook]: " RPI_SERVICE
RPI_SERVICE="${RPI_SERVICE:-kr_notebook}"

read -p "Build features (comma-separated, or empty) []: " BUILD_FEATURES
BUILD_FEATURES="${BUILD_FEATURES:-}"

cat > "$PROJECT_DIR/.rpi-deploy.conf" << EOF
# RPi deployment configuration
# Generated by rpi-setup.sh

# SSH connection
RPI_SSH="$RPI_SSH"

# Paths on RPi
RPI_INSTALL_DIR="$RPI_INSTALL_DIR"
RPI_SERVICE="$RPI_SERVICE"

# Build settings
TARGET="$TARGET"
USE_CROSS=$USE_CROSS
BUILD_FEATURES="$BUILD_FEATURES"
EOF

echo ""
echo "  Created .rpi-deploy.conf"

echo ""
echo "=== Setup Complete ==="
echo ""
echo "Deploy with: ./scripts/rpi-deploy.sh"
